Using Python

In [1]:
import pandas as pd

In [2]:
data = {'Feature 1': [1, 20, 3, 40, 5],
        'Feature 2': [6, 7, 18, 19, 10]}

df = pd.DataFrame(data)
df.head()

   Feature 1  Feature 2
0          1          6
1         20          7
2          3         18
3         40         19
4          5         10

In [3]:
def standardize_data(data):
    mean = data.mean()
    std_dev = data.std() # delta degree of freedom ddof=0
    standardized_data_raw = (data - mean) / std_dev
    return standardized_data_raw

In [4]:
standardized_df_raw = df.apply(standardize_data)

In [5]:
print("Original DataFrame:")
print(df)
print("\nStandardized DataFrame:")
print(standardized_df_raw)

Original DataFrame:
   Feature 1  Feature 2
0          1          6
1         20          7
2          3         18
3         40         19
4          5         10

Standardized DataFrame:
   Feature 1  Feature 2
0  -0.777975  -0.979796
1   0.376832  -0.816497
2  -0.656417   0.979796
3   1.592418   1.143095
4  -0.534858  -0.326599

In [6]:
df.head()

   Feature 1  Feature 2
0          1          6
1         20          7
2          3         18
3         40         19
4          5         10

In [7]:
standardized_df_raw.head()

   Feature 1  Feature 2
0  -0.777975  -0.979796
1   0.376832  -0.816497
2  -0.656417   0.979796
3   1.592418   1.143095
4  -0.534858  -0.326599

In [ ]:
standardized_df_raw['Feature 1'].mean() 
#Result 1 If we add 1 we see the result

np.float64(-4.4408920985006264e-17)

In [23]:
#Result 1 If we add 1 we see the result
standardized_df_raw['Feature 1'].mean() + 1

np.float64(1.0)

In [16]:
standardized_df_raw['Feature 1'].std()

np.float64(0.9999999999999999)

Sklearn

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
df

   Feature 1  Feature 2
0          1          6
1         20          7
2          3         18
3         40         19
4          5         10

In [19]:
scaler = StandardScaler()
standardized_data = scaler.fit_transform(df)
standardized_df = pd.DataFrame(standardized_data, columns=df.columns)

In [20]:
print("Original DataFrame:")
print(df)

print("\nStandardized DataFrame: raw code")
print(standardized_df_raw)

print("\nStandardized DataFrame: sklearn")
print(standardized_df)

Original DataFrame:
   Feature 1  Feature 2
0          1          6
1         20          7
2          3         18
3         40         19
4          5         10

Standardized DataFrame: raw code
   Feature 1  Feature 2
0  -0.777975  -0.979796
1   0.376832  -0.816497
2  -0.656417   0.979796
3   1.592418   1.143095
4  -0.534858  -0.326599

Standardized DataFrame: sklearn
   Feature 1  Feature 2
0  -0.869803  -1.095445
1   0.421311  -0.912871
2  -0.733896   1.095445
3   1.780378   1.278019
4  -0.597989  -0.365148